Eres un analista educativo y debes evaluar el rendimiento de un grupo de estudiantes en varias asignaturas. Dispones de una matriz con las calificaciones obtenidas por cada estudiante en distintas materias. Para analizar los datos, se te pide:

### Tareas:

- **Calcular la norma L1 y la norma L2** de las calificaciones de cada estudiante para medir la dispersión y la magnitud de sus puntuaciones.
- **Calcular la norma L1 y la norma L2** para cada asignatura para entender lo variadas que son las calificaciones en cada materia.
- **Utilizar `axis=1`** para obtener las puntuaciones totales de cada estudiante (sumando todas las asignaturas).
- **Utilizar `axis=0`** para obtener las puntuaciones totales de cada asignatura (sumando las calificaciones de todos los alumnos).
- **Aplicar `keepdims=True`** para mantener la estructura de la matriz al realizar las operaciones y evitar problemas de dimensión.
    
    ```python
    #Datos de entrada
    calificaciones = np.array([
        [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
        [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
        [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
        [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
        [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
        [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
        [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
        [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
        [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
        [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
        [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
        [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
        [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
        [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
        [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
        [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
        [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
        [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
        [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
        [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
        [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
        [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
        [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
        [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
        [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
        [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
        [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
        [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
        [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
        [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
        [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
        [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
        [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
        [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
        [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
        [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
        [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
        [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
        [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
        [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
        [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
        [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
        [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
        [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
        [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
        [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
        [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
        [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
        [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
    ])
    
    ```
    
    ### Preguntas:
    
    - ¿Por qué la norma L1 representa la suma absoluta de las calificaciones?
    - ¿Por qué la norma L2 nos da una idea de la magnitud total de los valores, penalizando más las notas altas?
    - ¿Cómo afecta `keepdims=True` en las operaciones realizadas?

In [1]:
import numpy as np 

In [21]:
#Datos de entrada
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])

def distancia_euclidiana(p1):
    return np.linalg.norm(p1)

'''
for i,e in enumerate(calificaciones):
    print(f"Estudiante {i+1}: {distancia_euclidiana(e)}")'''

np.linalg.norm(calificaciones, axis =1, keepdims = True)


array([[235.98516903],
       [231.79301111],
       [246.02032436],
       [243.73756379],
       [227.02643018],
       [247.06679259],
       [226.08626672],
       [242.8147442 ],
       [246.27829787],
       [244.45040397],
       [246.81166909],
       [250.09598158],
       [238.03991262],
       [226.0398195 ],
       [244.64055265],
       [244.44426768],
       [235.94490882],
       [247.03441056],
       [236.88182708],
       [256.18547968],
       [247.72161795],
       [254.58593834],
       [242.72412323],
       [249.45540684],
       [247.95765768],
       [223.57996332],
       [253.42454498],
       [233.13515393],
       [245.56261931],
       [249.8559585 ],
       [247.45100525],
       [240.72390824],
       [257.42571744],
       [255.286114  ],
       [250.79473679],
       [245.875985  ],
       [244.90202122],
       [245.29370151],
       [262.27275878],
       [257.62375667],
       [260.18262817],
       [261.52437745],
       [247.09512338],
       [248

In [22]:
'''for i,e in enumerate(calificaciones.T):
    print(f"Asignatura {i+1}: {distancia_euclidiana(e)}")'''

np.linalg.norm(calificaciones, axis = 0, keepdims = True)

array([[560.86986013, 545.80032979, 551.05807316, 552.24632185,
        534.66905652, 549.20032775, 534.83455386, 529.10395954,
        528.89129318, 549.85179821]])

In [20]:
puntuaciones_totales_estudiante = np.sum(calificaciones, axis = 1, keepdims = True)
print(puntuaciones_totales_estudiante)


[[737]
 [720]
 [766]
 [756]
 [705]
 [774]
 [709]
 [763]
 [773]
 [762]
 [774]
 [780]
 [743]
 [710]
 [769]
 [765]
 [742]
 [774]
 [739]
 [803]
 [776]
 [798]
 [763]
 [782]
 [779]
 [702]
 [796]
 [734]
 [769]
 [786]
 [778]
 [754]
 [806]
 [803]
 [788]
 [771]
 [765]
 [771]
 [823]
 [808]
 [817]
 [823]
 [772]
 [781]
 [776]
 [745]
 [808]
 [753]
 [803]]


In [19]:
puntuaciones_totales_asignatura = np.sum(calificaciones, axis = 0, keepdims = True)
print(puntuaciones_totales_asignatura)

[[3895 3788 3827 3828 3707 3807 3710 3659 3668 3805]]
