### **Contexto**

Eres un analista de rendimiento deportivo y tienes un equipo de **fútbol** que ha jugado **una temporada completa**. Para evaluar a cada jugador, has recopilado sus estadísticas en diferentes categorías:

- **Goles marcados**
- **Asistencias**
- **Pases completados**
- **Regates exitosos**
- **Tiros a puerta**

Sin embargo, los valores en cada categoría tienen escalas diferentes, por lo que es difícil comparar directamente el desempeño de los jugadores. Para resolver este problema, aplicarás la **normalización con la norma L2**, lo que permitirá convertir todas las estadísticas a una escala comparable.

### **Objetivo del ejercicio**

1. Representar el rendimiento de los jugadores como una matriz en NumPy.
2. Aplicar la **normalización L2** a cada jugador para escalar sus valores entre 0 y 1 mientras se mantiene la proporción relativa.
3. Comparar los jugadores después de la normalización.

### **Datos de entrada**

Supongamos que tenemos los datos de 5 jugadores:

| Jugador | Goles | Asistencias | Pases | Regates | Tiros a puerta |
| --- | --- | --- | --- | --- | --- |
| Jugador 1 | 10 | 7 | 300 | 25 | 40 |
| Jugador 2 | 15 | 10 | 250 | 30 | 50 |
| Jugador 3 | 5 | 12 | 280 | 20 | 35 |
| Jugador 4 | 8 | 6 | 310 | 15 | 38 |
| Jugador 5 | 12 | 9 | 270 | 28 | 45 |

Cada jugador es un **vector** con 5 componentes. Aplicaremos la **norma L2** para normalizar sus estadísticas.

### **Tareas**

1. Representar los datos como una matriz en NumPy.
2. Aplicar la normalización L2 a cada jugador (por filas, usando `axis=1`).
3. Mostrar los valores normalizados y analizar cómo se comparan los jugadores tras la normalización.

### Preguntas

- ¿Cómo cambian los valores después de la normalización?
- ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
- ¿Qué pasaría si normalizamos por **columnas (axis=0)** en lugar de por filas?

In [1]:
import numpy as np

In [2]:
jugadores = np.array([[10,7,300,25,40],
                      [15,10,250,30,50],
                      [5,12,280,20,35],
                      [8,6,310,15,38],
                      [12,9,270,28,45]
                      ])
print(jugadores)

[[ 10   7 300  25  40]
 [ 15  10 250  30  50]
 [  5  12 280  20  35]
 [  8   6 310  15  38]
 [ 12   9 270  28  45]]


In [11]:
normalizacion = jugadores / np.linalg.norm(jugadores, axis = 1, keepdims= True)
print(normalizacion)

[[0.03290221 0.02303155 0.98706643 0.08225554 0.13160886]
 [0.05828815 0.03885877 0.97146918 0.1165763  0.19429384]
 [0.01765627 0.04237506 0.98875136 0.0706251  0.12359392]
 [0.02557216 0.01917912 0.9909212  0.0479478  0.12146776]
 [0.04354749 0.03266062 0.97981848 0.10161081 0.16330308]]
