### **Contexto:**

Eres un ingeniero de datos en un equipo de Fórmula 1 y debes analizar el rendimiento de **10 pilotos** en **5 carreras**. Para ello, trabajarás con matrices en NumPy para transformar los datos y extraer información útil.

### **Tareas:**

1. **Representar los datos** en un array bidimensional de NumPy donde cada fila sea un piloto y cada columna una carrera.
2. **Transformación de arrays:**
    - Reorganiza la matriz con `.reshape()` para analizar los datos de otra manera.
    - Usa `.ravel()` o `.flatten()` para convertir la matriz en un array 1D.
3. **Operaciones aritméticas:**
    - Calcula el promedio de posiciones por piloto y por carrera (`axis=0` y `axis=1`).
    - Aplica una penalización sumando una constante a cada posición y recalculando los valores.
4. **Producto escalar:**
    - Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el **producto escalar**.
5. **Producto cruzado:**
    - Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su **producto cruzado**, interpretando el resultado en términos de diferencias de rendimiento.
6. **Extra bonus:**
    - Normaliza los datos usando la **norma L2** (`np.linalg.norm()`) para comparar el rendimiento de los pilotos en diferentes circuitos.

In [2]:
import numpy as np 

In [4]:
pilotos = np.array([[1,1,4,5,3], 
                    [2,3,5,4,1], 
                    [3,2,3,1,2], 
                    [4,4,2,2,4], 
                    [5,5,1,3,5],
                    [1,1,4,5,3], 
                    [2,3,5,4,1], 
                    [3,2,3,1,2], 
                    [4,4,2,2,4], 
                    [5,5,1,3,5]])
print(pilotos)

[[1 1 4 5 3]
 [2 3 5 4 1]
 [3 2 3 1 2]
 [4 4 2 2 4]
 [5 5 1 3 5]
 [1 1 4 5 3]
 [2 3 5 4 1]
 [3 2 3 1 2]
 [4 4 2 2 4]
 [5 5 1 3 5]]


In [8]:
print(pilotos.reshape(10,5,1))

[[[1]
  [1]
  [4]
  [5]
  [3]]

 [[2]
  [3]
  [5]
  [4]
  [1]]

 [[3]
  [2]
  [3]
  [1]
  [2]]

 [[4]
  [4]
  [2]
  [2]
  [4]]

 [[5]
  [5]
  [1]
  [3]
  [5]]

 [[1]
  [1]
  [4]
  [5]
  [3]]

 [[2]
  [3]
  [5]
  [4]
  [1]]

 [[3]
  [2]
  [3]
  [1]
  [2]]

 [[4]
  [4]
  [2]
  [2]
  [4]]

 [[5]
  [5]
  [1]
  [3]
  [5]]]


In [9]:
print(pilotos.flatten())

[1 1 4 5 3 2 3 5 4 1 3 2 3 1 2 4 4 2 2 4 5 5 1 3 5 1 1 4 5 3 2 3 5 4 1 3 2
 3 1 2 4 4 2 2 4 5 5 1 3 5]


In [11]:
promedio_carrera = pilotos.mean(axis = 0, keepdims = True)
promedio_piloto = pilotos.mean(axis = 1, keepdims = True)
print(promedio_carrera)
print(promedio_piloto)
penalizacion = pilotos + 1
promedio_carrera = penalizacion.mean(axis = 0, keepdims = True)
promedio_piloto = penalizacion.mean(axis = 1, keepdims = True)
print(promedio_carrera)
print(promedio_piloto)

[[3. 3. 3. 3. 3.]]
[[2.8]
 [3. ]
 [2.2]
 [3.2]
 [3.8]
 [2.8]
 [3. ]
 [2.2]
 [3.2]
 [3.8]]
[[4. 4. 4. 4. 4.]]
[[3.8]
 [4. ]
 [3.2]
 [4.2]
 [4.8]
 [3.8]
 [4. ]
 [3.2]
 [4.2]
 [4.8]]


In [12]:
vector1 = pilotos[0]
vector2 = pilotos[1]
producto_escalar = np.dot(vector1, vector2)
print(producto_escalar)

48


In [13]:
piloto1 = [1,2,2]
piloto2 = [2,3,3]
producto_cruzado = np.cross(piloto1, piloto2)
print(producto_cruzado)

[ 0  1 -1]


In [14]:
normalizado = pilotos / np.linalg.norm(pilotos, axis = 1, keepdims = True)
print(normalizado)

[[0.13867505 0.13867505 0.5547002  0.69337525 0.41602515]
 [0.26967994 0.40451992 0.67419986 0.53935989 0.13483997]
 [0.57735027 0.38490018 0.57735027 0.19245009 0.38490018]
 [0.53452248 0.53452248 0.26726124 0.26726124 0.53452248]
 [0.54232614 0.54232614 0.10846523 0.32539569 0.54232614]
 [0.13867505 0.13867505 0.5547002  0.69337525 0.41602515]
 [0.26967994 0.40451992 0.67419986 0.53935989 0.13483997]
 [0.57735027 0.38490018 0.57735027 0.19245009 0.38490018]
 [0.53452248 0.53452248 0.26726124 0.26726124 0.53452248]
 [0.54232614 0.54232614 0.10846523 0.32539569 0.54232614]]
