In [2]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array1)
print(array2d)
print(array3d)

zeros = np.zeros((4, 6))
print(zeros)

range_array = np.arange(0, 10, 4)
print(range_array)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0 4 8]


In [2]:
random1 = np.random.random((2,2))
print(random1)

random2 = np.random.randint(0,10,(2,2))
print(random2)

espacio = np.linspace(0,1000,2)
print(espacio)

[[0.02865613 0.4421303 ]
 [0.75396568 0.29836888]]
[[3 7]
 [2 0]]
[   0. 1000.]


In [3]:
reverse = np.arange(10,0,-1)
print(reverse)
print(reverse[4:9:2])
print(reverse[1:10:3])
print(reverse[2:9:2])
print(reverse[0:-1:5][::-1]) 
print(reverse[5:9:1][::-1])

[10  9  8  7  6  5  4  3  2  1]
[6 4 2]
[9 6 3]
[8 6 4 2]
[ 5 10]
[2 3 4 5]


In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[1:,1:])

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]  
])

print(array_3d[1,2])
print(array_3d[2,1,1])
print(array_3d[:,1,0])

[[5 6]
 [8 9]]
[16 17 18]
23
[ 4 13 22]


1. **Crear un array unidimensional con el nombre de los productos:** Tienes una lista de 5 productos: `"Smartphone"`, `"Tablet"`, `"Laptop"`, `"Auriculares"`, `"Teclado"`. Imprímelo.
2. **Crear un array bidimensional con la cantidad en stock de cada producto:** La tienda tiene el siguiente stock de productos:
    
    ```bash
    Smartphone - 50
    Tablet - 30
    Laptop - 15
    Auriculares - 40
    Teclado - 60
    ```
    
    Crea un array bidimensional donde cada fila represente un producto y las columnas representen el stock disponible en diferentes almacenes. Imprime el array.
    
3. **Crear un array tridimensional para registrar las ventas de cada producto durante una semana:** Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:
    
    ```bash
    Día 1: [5, 3, 2, 6, 4]
    Día 2: [7, 4, 1, 8, 5]
    Día 3: [6, 2, 3, 5, 4]
    ```
    
    Crea un array tridimensional que almacene esta información. Imprímelo.
    
4. **Crear un array de ceros para los productos no vendidos hoy:** Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array.
5. **Crear un array de unos para los productos que están en promoción:** Los productos en promoción tienen un valor de `1`, mientras que los que no están en promoción tienen `0`. Crea un array de unos y ceros, donde los productos en promoción tienen el valor `1`. Los productos en promoción son el `"Smartphone"` y el `"Teclado"`. Imprímelo.
6. **Crear un array con un rango de precios de productos:** La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función `np.arange`, y un paso de 50 unidades. Imprímelo.
7. **Crear un array de precios aleatorios:** Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo.
8. **Generar un array de números enteros aleatorios para la cantidad vendida:** Utiliza `np.random.randint` para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo.
9. **Crear un array vacío para almacenar los valores de descuento:** Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo.
10. **Generar un array con valores espaciados para analizar el cambio en las ventas:** Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza `np.linspace`para generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo.

In [27]:
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print(productos)
productos_stock = np.array([["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"], [50,30,15,40,60]])
print(productos_stock)
stock_dia = np.array([[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[5,3,2,6,2]],[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[7,4,1,8,5]],[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[6,2,3,5,4]]])
print(stock_dia)
zeros = np.zeros((5))
print(zeros)
unos = np.ones((5))
print(unos)

precios = np.arange(50,1000,50)
print(precios)

precios_aleatorios = np.random.randint(100,500,(5))
print(precios_aleatorios)
unidades_vendidas = np.random.randint(0,10,(5))
print(unidades_vendidas)

vacio = np.empty((5))
print(vacio)

ventas = np.linspace(0, 1000, 5)
print(ventas)

['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
[['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
 ['50' '30' '15' '40' '60']]
[[['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['5' '3' '2' '6' '2']]

 [['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['7' '4' '1' '8' '5']]

 [['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['6' '2' '3' '5' '4']]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900
 950]
[429 105 460 145 194]
[3 9 0 9 9]
[1. 1. 1. 1. 1.]
[   0.  250.  500.  750. 1000.]


En este ejercicio, trabajarás con arrays 1D y 2D en NumPy, aplicando indexación y selección de elementos.

### Tareas:

1. **Creación de arrays**
    - Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
    - Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
2. **Indexación en arrays**
    - Extrae y muestra:
        - El primer y último elemento del array 1D.
        - El primer elemento de la primera fila del array 2D.
        - El último elemento de la última fila del array 2D.
        - El elemento ubicado en la segunda fila y tercera columna del array 2D.
3. **Selección de filas y columnas**
    - Extrae y muestra:
        - La primera fila completa del array 2D.
        - La segunda columna completa del array 2D.

In [3]:
array1 = np.arange(1,11)
print(array1)
array2 = np.arange(1,10).reshape(3,3)
print(array2)
print(array1[0])
print(array1[-1])
print(array2[0,0])
print(array2[2,2])
print(array2[1,2])
print(array2[0])
print(array2[:,1])

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
10
1
9
6
[1 2 3]
[4 5 6]


En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.

### Tareas:

1. **Creación del array 3D**
    - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
    - Usa `np.random.randint()` para generar valores enteros.
2. **Indexación en el array 3D**
    - Extrae y muestra:
        - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
        - El último píxel de la imagen (posición `[-1,-1]`).
        - El valor del canal rojo del píxel en la segunda fila y tercera columna.
3. **Slicing en el array 3D**
    - Extrae y muestra:
        - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
        - Solo los valores del canal azul para todos los píxeles de la imagen.
        - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).

In [4]:
array3 = np.random.randint(0,255,(4,4,3))
print(array3)
print(array3[0,0])
print(array3[-1,-1])
print(array3[:,1,2])
print(array3[:,0])
print(array3[:,:,2])
print(array3[1:3,1:3,:])

[[[ 83 127 137]
  [ 79 164 122]
  [208 192 154]
  [ 67  42  77]]

 [[198 194  59]
  [ 75 136 211]
  [ 33 176 143]
  [125 211 106]]

 [[ 82 251 199]
  [ 47 194  79]
  [129 203  92]
  [100 194  94]]

 [[ 67  95 196]
  [139 177  60]
  [135 130 248]
  [199  70 152]]]
[ 83 127 137]
[199  70 152]
[122 211  79  60]
[[ 83 127 137]
 [198 194  59]
 [ 82 251 199]
 [ 67  95 196]]
[[137 122 154  77]
 [ 59 211 143 106]
 [199  79  92  94]
 [196  60 248 152]]
[[[ 75 136 211]
  [ 33 176 143]]

 [[ 47 194  79]
  [129 203  92]]]


In [7]:
array = np.arange(25)
reshaped = array.reshape(5,5)
print(reshaped)
'''reshaped = array.reshape(2,4)
print(reshaped)'''
aplanado = reshaped.ravel()
print(aplanado)
transposed = reshaped.T
print(transposed)
reshaped3d = array.reshape(5,1,5)
print(reshaped3d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]

 [[20 21 22 23 24]]]


In [11]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
suma = array1 + array2
print(suma)
resta = array1 - array2
print(resta)
multiplicacion = array1 * array2
print(multiplicacion)
division = array1 / array2
print(division)
print(array1 + 6)
print(6 - array1)
print(array1 * 6)
print(array1 / 6)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 7  8]
 [ 9 10]]
[[5 4]
 [3 2]]
[[ 6 12]
 [18 24]]
[[0.16666667 0.33333333]
 [0.5        0.66666667]]


In [28]:
array = np.random.randint(0,26,25)
print(array)
print(np.cumsum(array))

array2 = np.random.rand(1,25)
print(array2)
print(np.cumsum(array2))



[13 18  6  5 17 16 21 13 20  5  7 21  8  7 11 12 22  9 13  5  5 25  7  5
 19]
[ 13  31  37  42  59  75  96 109 129 134 141 162 170 177 188 200 222 231
 244 249 254 279 286 291 310]
[[0.9041542  0.27698882 0.91073462 0.45139579 0.65284984 0.02763209
  0.54530186 0.62307754 0.69234964 0.61595639 0.39465846 0.33288993
  0.98942385 0.19489753 0.32586709 0.66802662 0.06971179 0.12414471
  0.56972007 0.39713331 0.99055224 0.9401889  0.53467106 0.27072756
  0.13277541]]
[ 0.9041542   1.18114301  2.09187763  2.54327342  3.19612327  3.22375536
  3.76905722  4.39213477  5.08448441  5.7004408   6.09509925  6.42798919
  7.41741304  7.61231057  7.93817766  8.60620429  8.67591607  8.80006078
  9.36978085  9.76691416 10.7574664  11.69765531 12.23232636 12.50305393
 12.63582934]


In [5]:
disco1 = np.array([10, 2, 150])
disco2 = np.array([20, 3, 200])
disco3 = np.array([30, 4, 250])

nuevo_disco = np.array([11, 2, 180])

discos = np.array([disco1, disco2, disco3])

def distancia_euclidiana(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))
#Otra forma: np.linalg.norm(v1 - v2)

distancias = [distancia_euclidiana(nuevo_disco, disco) for disco in discos]

indice_disco_mas_parecido = np.argmin(distancias)  
disco_mas_parecido = discos[indice_disco_mas_parecido]

print(f"El disco más similar al nuevo disco es: {disco_mas_parecido} con una distancia de {distancias[indice_disco_mas_parecido]:.2f}")

El disco más similar al nuevo disco es: [ 20   3 200] con una distancia de 21.95


In [10]:
vector1 = np.random.randint(0, 20, (3))
vector2 = np.random.randint(0, 20, (3))
print(vector1)
print(vector2)
producto_punto = np.dot(vector1, vector2)
print(producto_punto)
producto_cruzado = np.cross(vector1, vector2)
print(producto_cruzado)
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.cross(vector1,vector2))

[16  0  1]
[16 16 12]
268
[ -16 -176  256]
[-3  6 -3]


In [16]:
A = np.arange(5,20,5)
B = np.arange(100,400,100)
distancia1 = distancia = np.sqrt(np.sum((B - A) ** 2))
print(distancia1)
distancia1 = np.linalg.norm(A - B)
print(distancia1)

origen = distancia_origen = np.sqrt(np.sum(A ** 2))
print(origen)
origen = distancia_origen = np.sqrt(np.sum(B ** 2))
print(origen)
origen = np.linalg.norm(A)
print(origen)
origen = np.linalg.norm(B)
print(origen)


355.4574517435244
355.4574517435244
18.708286933869708
374.16573867739413
18.708286933869708
374.16573867739413
