In [2]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array1)
print(array2d)
print(array3d)

zeros = np.zeros((4, 6))
print(zeros)

range_array = np.arange(0, 10, 4)
print(range_array)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0 4 8]


In [3]:
random1 = np.random.random((2,2))
print(random1)

random2 = np.random.randint(0,10,(2,2))
print(random2)

espacio = np.linspace(0,1000,2)
print(espacio)

[[0.52702071 0.43184553]
 [0.59158929 0.17691012]]
[[0 7]
 [1 8]]
[   0. 1000.]


In [4]:
reverse = np.arange(10,0,-1)
print(reverse)
print(reverse[4:9:2])
print(reverse[1:10:3])
print(reverse[2:9:2])
print(reverse[0:-1:5][::-1]) 
print(reverse[5:9:1][::-1])

[10  9  8  7  6  5  4  3  2  1]
[6 4 2]
[9 6 3]
[8 6 4 2]
[ 5 10]
[2 3 4 5]


In [5]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[1:,1:])

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]  
])

print(array_3d[1,2])
print(array_3d[2,1,1])
print(array_3d[:,1,0])

[[5 6]
 [8 9]]
[16 17 18]
23
[ 4 13 22]


1. **Crear un array unidimensional con el nombre de los productos:** Tienes una lista de 5 productos: `"Smartphone"`, `"Tablet"`, `"Laptop"`, `"Auriculares"`, `"Teclado"`. Imprímelo.
2. **Crear un array bidimensional con la cantidad en stock de cada producto:** La tienda tiene el siguiente stock de productos:
    
    ```bash
    Smartphone - 50
    Tablet - 30
    Laptop - 15
    Auriculares - 40
    Teclado - 60
    ```
    
    Crea un array bidimensional donde cada fila represente un producto y las columnas representen el stock disponible en diferentes almacenes. Imprime el array.
    
3. **Crear un array tridimensional para registrar las ventas de cada producto durante una semana:** Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:
    
    ```bash
    Día 1: [5, 3, 2, 6, 4]
    Día 2: [7, 4, 1, 8, 5]
    Día 3: [6, 2, 3, 5, 4]
    ```
    
    Crea un array tridimensional que almacene esta información. Imprímelo.
    
4. **Crear un array de ceros para los productos no vendidos hoy:** Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array.
5. **Crear un array de unos para los productos que están en promoción:** Los productos en promoción tienen un valor de `1`, mientras que los que no están en promoción tienen `0`. Crea un array de unos y ceros, donde los productos en promoción tienen el valor `1`. Los productos en promoción son el `"Smartphone"` y el `"Teclado"`. Imprímelo.
6. **Crear un array con un rango de precios de productos:** La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función `np.arange`, y un paso de 50 unidades. Imprímelo.
7. **Crear un array de precios aleatorios:** Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo.
8. **Generar un array de números enteros aleatorios para la cantidad vendida:** Utiliza `np.random.randint` para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo.
9. **Crear un array vacío para almacenar los valores de descuento:** Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo.
10. **Generar un array con valores espaciados para analizar el cambio en las ventas:** Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza `np.linspace`para generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo.

In [6]:
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print(productos)
productos_stock = np.array([["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"], [50,30,15,40,60]])
print(productos_stock)
stock_dia = np.array([[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[5,3,2,6,2]],[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[7,4,1,8,5]],[["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"],[6,2,3,5,4]]])
print(stock_dia)
zeros = np.zeros((5))
print(zeros)
unos = np.ones((5))
print(unos)

precios = np.arange(50,1000,50)
print(precios)

precios_aleatorios = np.random.randint(100,500,(5))
print(precios_aleatorios)
unidades_vendidas = np.random.randint(0,10,(5))
print(unidades_vendidas)

vacio = np.empty((5))
print(vacio)

ventas = np.linspace(0, 1000, 5)
print(ventas)

['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
[['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
 ['50' '30' '15' '40' '60']]
[[['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['5' '3' '2' '6' '2']]

 [['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['7' '4' '1' '8' '5']]

 [['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
  ['6' '2' '3' '5' '4']]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900
 950]
[133 264 168 349 187]
[2 8 7 9 2]
[1. 1. 1. 1. 1.]
[   0.  250.  500.  750. 1000.]


En este ejercicio, trabajarás con arrays 1D y 2D en NumPy, aplicando indexación y selección de elementos.

### Tareas:

1. **Creación de arrays**
    - Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
    - Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
2. **Indexación en arrays**
    - Extrae y muestra:
        - El primer y último elemento del array 1D.
        - El primer elemento de la primera fila del array 2D.
        - El último elemento de la última fila del array 2D.
        - El elemento ubicado en la segunda fila y tercera columna del array 2D.
3. **Selección de filas y columnas**
    - Extrae y muestra:
        - La primera fila completa del array 2D.
        - La segunda columna completa del array 2D.

In [7]:
array1 = np.arange(1,11)
print(array1)
array2 = np.arange(1,10).reshape(3,3)
print(array2)
print(array1[0])
print(array1[-1])
print(array2[0,0])
print(array2[2,2])
print(array2[1,2])
print(array2[0])
print(array2[:,1])

[ 1  2  3  4  5  6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
10
0
8
5
[0 1 2]
[1 4 7]


En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.

### Tareas:

1. **Creación del array 3D**
    - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
    - Usa `np.random.randint()` para generar valores enteros.
2. **Indexación en el array 3D**
    - Extrae y muestra:
        - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
        - El último píxel de la imagen (posición `[-1,-1]`).
        - El valor del canal rojo del píxel en la segunda fila y tercera columna.
3. **Slicing en el array 3D**
    - Extrae y muestra:
        - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
        - Solo los valores del canal azul para todos los píxeles de la imagen.
        - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).

In [8]:
array3 = np.random.randint(0,256,(4,4,3))
print(array3)
print(array3[0,0])
print(array3[-1,-1])
print(array3[:,1,2])
print(array3[:,0])
print(array3[:,:,2])
print(array3[1:3,1:3,:])

[[[233 161 227]
  [ 76 169 230]
  [212 108 201]
  [ 24 193  87]]

 [[ 87 123 111]
  [190 137  88]
  [ 66 187 250]
  [187  83 117]]

 [[ 43 229 215]
  [ 13 126 137]
  [114 174 214]
  [  3 252  65]]

 [[111 192  32]
  [144 191 125]
  [ 98 224   5]
  [178 231  58]]]
[233 161 227]
[178 231  58]
[230  88 137 125]
[[233 161 227]
 [ 87 123 111]
 [ 43 229 215]
 [111 192  32]]
[[227 230 201  87]
 [111  88 250 117]
 [215 137 214  65]
 [ 32 125   5  58]]
[[[190 137  88]
  [ 66 187 250]]

 [[ 13 126 137]
  [114 174 214]]]


In [9]:
array = np.arange(25)
reshaped = array.reshape(5,5)
print(reshaped)
'''reshaped = array.reshape(2,4)
print(reshaped)'''
aplanado = reshaped.ravel()
print(aplanado)
transposed = reshaped.T
print(transposed)
reshaped3d = array.reshape(5,1,5)
print(reshaped3d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]

 [[20 21 22 23 24]]]


In [10]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
suma = array1 + array2
print(suma)
resta = array1 - array2
print(resta)
multiplicacion = array1 * array2
print(multiplicacion)
division = array1 / array2
print(division)
print(array1 + 6)
print(6 - array1)
print(array1 * 6)
print(array1 / 6)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 7  8]
 [ 9 10]]
[[5 4]
 [3 2]]
[[ 6 12]
 [18 24]]
[[0.16666667 0.33333333]
 [0.5        0.66666667]]


In [11]:
array = np.random.randint(0,26,25)
print(array)
print(np.cumsum(array))

array2 = np.random.rand(1,25)
print(array2)
print(np.cumsum(array2))



[ 2  8 15 19  8 18  8  5  6  6 14  1  1  1  6 17 22 12  8  8  9  2 18 13
  5]
[  2  10  25  44  52  70  78  83  89  95 109 110 111 112 118 135 157 169
 177 185 194 196 214 227 232]
[[0.3076911  0.61479179 0.89936018 0.72539617 0.30557067 0.1124666
  0.70394406 0.45429556 0.34086179 0.16659691 0.98466915 0.68039672
  0.09583176 0.61229363 0.41755874 0.64293507 0.71584322 0.58180494
  0.38973055 0.21254297 0.4462247  0.38492832 0.74075294 0.46359472
  0.18593267]]
[ 0.3076911   0.9224829   1.82184307  2.54723925  2.85280992  2.96527652
  3.66922058  4.12351614  4.46437793  4.63097484  5.61564399  6.29604071
  6.39187246  7.0041661   7.42172484  8.06465991  8.78050313  9.36230807
  9.75203862  9.96458159 10.41080629 10.79573461 11.53648755 12.00008227
 12.18601493]


In [12]:
disco1 = np.array([10, 2, 150])
disco2 = np.array([20, 3, 200])
disco3 = np.array([30, 4, 250])

nuevo_disco = np.array([11, 2, 180])

discos = np.array([disco1, disco2, disco3])

def distancia_euclidiana(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))
#Otra forma: np.linalg.norm(v1 - v2)

distancias = [distancia_euclidiana(nuevo_disco, disco) for disco in discos]

indice_disco_mas_parecido = np.argmin(distancias)  
disco_mas_parecido = discos[indice_disco_mas_parecido]

print(f"El disco más similar al nuevo disco es: {disco_mas_parecido} con una distancia de {distancias[indice_disco_mas_parecido]:.2f}")

El disco más similar al nuevo disco es: [ 20   3 200] con una distancia de 21.95


In [13]:
vector1 = np.random.randint(0, 20, (3))
vector2 = np.random.randint(0, 20, (3))
print(vector1)
print(vector2)
producto_punto = np.dot(vector1, vector2)
print(producto_punto)
producto_cruzado = np.cross(vector1, vector2)
print(producto_cruzado)
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.cross(vector1,vector2))

[17  6 14]
[ 9 17 13]
437
[-160  -95  235]
[-3  6 -3]


In [14]:
A = np.arange(5,20,5)
B = np.arange(100,400,100)
distancia1 = distancia = np.sqrt(np.sum((B - A) ** 2))
print(distancia1)
distancia1 = np.linalg.norm(A - B)
print(distancia1)

origen = distancia_origen = np.sqrt(np.sum(A ** 2))
print(origen)
origen = distancia_origen = np.sqrt(np.sum(B ** 2))
print(origen)
origen = np.linalg.norm(A)
print(origen)
origen = np.linalg.norm(B)
print(origen)


355.4574517435244
355.4574517435244
18.708286933869708
374.16573867739413
18.708286933869708
374.16573867739413
