In [20]:
import numpy as np
from sklearn.metrics import root_mean_squared_error

1-1- Crea dos vectores con 10 valores aleatorios int entre 30 y 60 (vector 1) y con 10 valores float del 0.1 al 9.9 (vector 2) 
2-El primer vector se corresponderá con el valor real y el segundo vector con el valor predicho por el modelo
3-Calcula el RMSE con la función root_mean_squared_error de Scikit Learn y además también utilizando la forma tradicional
4- Imprime el resultado de ambas formas.
5- ¿Hay diferencia entre los resultados?

In [15]:
v_real = np.random.randint(30,60,10)
print(v_real)
v_predicho = np.random.uniform(0.1,9.9,10)
print(v_predicho)
rmse_sklearn = root_mean_squared_error(v_real, v_predicho)  
print("RMSE con Scikit-learn:", rmse_sklearn)


[42 34 47 47 41 45 53 31 47 58]
[7.89082854 3.3492115  2.72665397 1.105429   7.65038966 5.22814552
 3.87230879 7.05633418 4.3338161  2.0029822 ]
RMSE con Scikit-learn: 40.99541751878554


In [16]:
errors = (v_real - v_predicho) ** 2
mse = np.mean(errors)
rmse = np.sqrt(mse) 
print(f"RMSE: {rmse}")

RMSE: 40.99541751878554


### **Contexto:**

Los datos con sesgo positivo pueden beneficiarse de una transformación mediante raíz cuadrada para acercarlos a una distribución normal.

### **Tareas:**

1. Crea un array de valores que sigan una progresión exponencial, por ejemplo: `[1, 10, 100, 1000, 10000]`.
2. Aplica la transformación de raíz cuadrada utilizando `np.sqrt()`.
3. Imprime los valores originales y los valores transformados.

In [20]:
v = np.array([10**e for e in range(0,5)])
r = np.sqrt(v)
print(f"Valor real: {v}")
print(f"Valor transformado: {r}")

Valor real: [    1    10   100  1000 10000]
Valor transformado: [  1.           3.16227766  10.          31.6227766  100.        ]


### **Contexto:**

El RMSE es una métrica común en Machine Learning para evaluar la precisión de un modelo.

### **Tareas:**

1. Define dos arrays: uno con valores reales (`y`) y otro con valores predichos (`y_pred`).
2. Calcula el error cuadrático medio (MSE) elevando al cuadrado las diferencias entre `y` y `y_pred`, promediando los valores y tomando la raíz cuadrada.
3. Imprime el resultado del RMSE.
4. Repite el cálculo utilizando la función `root_mean_squared_error` de `sklearn.metrics`.

In [21]:
y = np.random.randint(1,10,10)
print(y)
y_pred = np.random.uniform(0.1,9.9,10)
print(y_pred)
errors = (y - y_pred) ** 2
mse = np.mean(errors)
rmse = np.sqrt(mse) 
print(f"RMSE: {rmse}")
rmse_sklearn = root_mean_squared_error(y, y_pred)  
print("RMSE con Scikit-learn:", rmse_sklearn)

[2 4 6 4 4 9 5 6 6 5]
[0.25018637 0.25090159 8.66905425 3.2909604  0.58828229 1.04929294
 4.78122222 6.56606635 4.35164696 2.13879729]
RMSE: 3.329708370244919
RMSE con Scikit-learn: 3.329708370244919


### **Contexto:**

Softmax convierte logits en probabilidades normalizadas para clasificación en modelos de Machine Learning.

### **Tareas:**

1. Define un array con tres valores representando logits de un modelo.
2. Aplica la función exponencial a cada valor y normaliza dividiendo entre la suma total.
3. Imprime las probabilidades resultantes.
4. Implementa el cálculo de softmax utilizando las funciones de `scipy.special.softmax` y `sklearn.utils.extmath.softmax`. Compara los resultados.

In [29]:
logits = np.array([2.0, 1.0, 0.1])
exp = np.exp(logits)
norm = exp / np.sum(exp)
print(norm) 

[0.65900114 0.24243297 0.09856589]


In [33]:
from sklearn.utils.extmath import softmax

probabilities_sklearn = softmax(logits.reshape(1, -1))[0]
print("Probabilidades softmax con Scikit-learn:", probabilities_sklearn)

Probabilidades softmax con Scikit-learn: [0.65900114 0.24243297 0.09856589]


In [31]:
from scipy.special import softmax

probabilities = softmax(logits)
print("Probabilidades softmax con Spicy:", probabilities)

Probabilidades softmax con Spicy: [0.65900114 0.24243297 0.09856589]


In [15]:
import pandas as pd 

df = pd.read_csv("Product_v6.csv")
df.columns = df.columns.str.strip()
print("Todas las columnas:", df.columns) 
df["value"] = df["value"].astype(int)
df.iloc[1,4]



Todas las columnas: Index(['partNumber', 'productType', 'category.code', 'brand.code',
       'family.code', 'line.code', 'productSegment.code', 'status', 'value',
       'valueCurrency', 'defaultQuantityUnits', 'name', 'description',
       'plannerCode', 'sourceLink'],
      dtype='object')


'Alliance'

In [17]:
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_columns', None) 
#df

In [ ]:
df = pd.read_csv("Product_v6.csv")
value = np.array(df["value"])
print(value)
resultado = np.sqrt(value)
print(resultado)
df["raiz_cuadrada"] = resultado
df.to_csv("datos_modificados.csv", index = False)
df.head()

[1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03
 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03
 0.000e+00 0.000e+00 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03
 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 1.250e+03 0.000e+00
 0.000e+00 1.450e+03 1.450e+03 0.000e+00 0.000e+00 1.000e+02 2.500e+02
 1.250e+02 5.500e+01 4.800e+01 5.100e+01 7.800e+01 8.800e+01 9.300e+01
 1.200e+02 2.890e+02 1.830e+02 9.500e+01 1.080e+02 3.200e+02 3.500e+02
 5.000e+01 4.120e+02 4.220e+02 4.550e+02 1.220e+02 5.500e+01 5.500e+01
 5.500e+01 5.500e+01 5.500e+01 1.900e+02 2.030e+02 1.120e+02 1.890e+02
 9.500e+02 7.740e+02 7.740e+02 7.740e+02 7.740e+02 5.000e+00 1.900e+01
 3.000e+00 2.400e+01 3.000e+00 1.290e+03 1.180e+03 9.900e+02 1.452e+03
 2.398e+03 4.592e+03 5.530e+03 2.349e+03 1.287e+03 1.456e+03 8.330e+02
 1.032e+03 9.760e+02]
[35.35533906 35.35533906 35.35533906 35.35533906 35.35533906 35.35533906
 35.35533906 35.35533906 35.35533906 35.35533906 35.3

partNumber productType       category.code brand.code family.code  \
81   83600200        ITEM  Primary Foundation        NaN         NaN   
82   83600300        ITEM  Primary Foundation        NaN         NaN   
83    9664145        ITEM   Secondary Chassis        NaN         NaN   
84    9664146        ITEM   Secondary Chassis        NaN         NaN   
85    9664147        ITEM   Secondary Chassis        NaN         NaN   

   line.code  productSegment.code    status   value valueCurrency  \
81       NaN                  NaN    ACTIVE  1287.0          USD    
82       NaN                  NaN  INACTIVE  1456.0          USD    
83       NaN                  NaN    ACTIVE   833.0          USD    
84       NaN                  NaN    ACTIVE  1032.0          USD    
85       NaN                  NaN    ACTIVE   976.0          USD    

   defaultQuantityUnits                                 name  \
81                  EA   Light Pole Foundation, 24" Diameter   
82                  EA   Light Pole Foundation, 30" Diameter   
83                  EA           Bracket Al Tapered 6' Reach   
84                  EA           Bracket Al Tapered 8' Reach   
85                  EA            Bracket Al Tapered 7' Rise   

                                          description  plannerCode  \
81  Primary Foundation - Light Pole Foundation, 24...  Mechanicals   
82  Primary Foundation - Light Pole Foundation, 30...  Mechanicals   
83    Secondary Chassis - Bracket Al Tapered 6' Reach  Mechanicals   
84    Secondary Chassis - Bracket Al Tapered 8' Reach  Mechanicals   
85     Secondary Chassis - Bracket Al Tapered 7' Rise  Mechanicals   

                       sourceLink  raiz_cuadrada  
81  http://lighttree.com/83600200      35.874782  
82  http://lighttree.com/83600300      38.157568  
83   http://lighttree.com/9664145      28.861739  
84   http://lighttree.com/9664146      32.124757  
85   http://lighttree.com/9664147      31.240999

In [33]:
df["R.C BRUTA"] = df["raiz_cuadrada"] * 0.9
df.head()

partNumber productType    category.code     brand.code      family.code  \
0  PS-SL-A287     PRODUCT  Street Lighting  Public Sector         Alliance   
1  PS-SL-A288     PRODUCT  Street Lighting  Public Sector         Alliance   
2  PS-SL-H309     PRODUCT  Street Lighting  Public Sector             Helm   
3  PS-SL-H310     PRODUCT  Street Lighting  Public Sector             Helm   
4  PS-SL-F342     PRODUCT  Street Lighting  Public Sector  Flatbush Avenue   

  line.code  productSegment.code  status   value valueCurrency  \
0     Rural                  NaN  ACTIVE  1250.0          USD    
1     Rural                  NaN  ACTIVE  1250.0          USD    
2     Rural                  NaN  ACTIVE  1250.0          USD    
3     Rural                  NaN  ACTIVE  1250.0          USD    
4      City                  NaN  ACTIVE  1250.0          USD    

  defaultQuantityUnits                                               name  \
0                  EA    Alliance 150W HPS 25' Luminaire and Pole, Silver   
1                  EA    Alliance 100W HPS 25' Luminaire and Pole, Silver   
2                  EA         Helm 150W HPS 30' Luminaire and Pole, Black   
3                  EA         Helm 100W HPS 30' Luminaire and Pole, Black   
4                  EA   Flatbush Avenue Twin 250W 30' Teardrop Lumi. a...   

                                         description plannerCode  \
0  Public Sector Street Lighting - Alliance 150W ...    Lighting   
1  Public Sector Street Lighting - Alliance 100W ...    Lighting   
2  Public Sector Street Lighting - Helm 150W HPS ...    Lighting   
3  Public Sector Street Lighting - Helm 100W HPS ...    Lighting   
4  Public Sector Street Lighting - Flatbush Avenu...    Lighting   

                        sourceLink  raiz_cuadrada  raiz_cuadrada_10  R.C BRUTA  
0  http://lighttree.com/PS-SL-A287      28.637825         25.774042  25.774042  
1  http://lighttree.com/PS-SL-A288      28.637825         25.774042  25.774042  
2  http://lighttree.com/PS-SL-H309      28.637825         25.774042  25.774042  
3  http://lighttree.com/PS-SL-H310      28.637825         25.774042  25.774042  
4  http://lighttree.com/PS-SL-F342      28.637825         25.774042  25.774042

In [45]:
df.loc[(60 > df["R.C BRUTA"]) & (df["R.C BRUTA"] > 40), "R.C BRUTA"] ** 2

78    2440.377072
79    2938.868730
Name: R.C BRUTA, dtype: float64

In [51]:
df["R.C BRUTA"][(60 > df["R.C BRUTA"]) & (df["R.C BRUTA"] > 40)] ** 2

78    2440.377072
79    2938.868730
Name: R.C BRUTA, dtype: float64

In [29]:
import numpy as np 
np.random.seed(42)
array = np.random.randint(0, 100, (2, 3))
print(array)
ordenado = np.sort(array, axis = 0)
ordenado_filas = np.sort(array)
print(ordenado)
print(ordenado_filas)

[[51 92 14]
 [71 60 20]]
[[51 60 14]
 [71 92 20]]
[[14 51 92]
 [20 60 71]]


In [32]:
strings = np.array(["casa","casanova","ana","andamio","perro","pértiga","tucán","tucumán"])
ordenado = np.sort(strings)
print(ordenado)

['ana' 'andamio' 'casa' 'casanova' 'perro' 'pértiga' 'tucumán' 'tucán']


In [41]:
edades = np.random.randint(1,90,(10))
print(edades)
resultado = np.where(edades > 37, "Adultos", "Jóvenes")
resultado2 = np.where(edades > 37)
print(resultado)
print(resultado2[0])

[51 55 64  3 51  7 21 73 39 18]
['Adultos' 'Adultos' 'Adultos' 'Jóvenes' 'Adultos' 'Jóvenes' 'Jóvenes'
 'Adultos' 'Adultos' 'Jóvenes']
[0 1 2 4 7 8]


In [57]:
notas = np.random.randint(1,100,(2,2,2,2,2))
print(notas)
print("--------------------------------------------------")
notas[notas < 50] = 50
print(notas)

[[[[[81 59]
    [ 2  2]]

   [[92 54]
    [87 96]]]


  [[[97  1]
    [19  2]]

   [[53 44]
    [90 32]]]]



 [[[[70 32]
    [68 55]]

   [[75 56]
    [17 38]]]


  [[[24 69]
    [98 70]]

   [[86 11]
    [16 97]]]]]
--------------------------------------------------
[[[[[81 59]
    [50 50]]

   [[92 54]
    [87 96]]]


  [[[97 50]
    [50 50]]

   [[53 50]
    [90 50]]]]



 [[[[70 50]
    [68 55]]

   [[75 56]
    [50 50]]]


  [[[50 69]
    [98 70]]

   [[86 50]
    [50 97]]]]]


In [72]:
import pandas as pd
import numpy as np

# Crear un DataFrame con valores aleatorios
df = pd.DataFrame({
    "id": range(1, 11),
    "ventas": np.random.randint(100, 1000, size=10)  # Números aleatorios entre 100 y 1000
})

# Agregar una columna con la media de 'ventas'
df["media_ventas"] = df["ventas"].mean()

print(df)

# CALCULAR LA MEDIANA

df["mediana_ventas"] = df["ventas"].median() # .median() devuelve el valor central de la distribución.
print(df)


# CALCULAR LA DESVIACIÓN ESTÁNDAR

df["desviacion_ventas"] = df["ventas"].std() #.std() calcula la dispersión de los datos respecto a la media.
print(df)

# NORMALIZAR VALORES CON MEDIA Y DESVIACIÓN ESTÁNDAR 

df["ventas_normalizadas"] = (df["ventas"] - df["ventas"].mean()) / df["ventas"].std() # Se aplica la fórmula de normalización Z-score: (X - media) / desviación estándar
print(df)

df["media_v_norm"] = df["ventas_normalizadas"].median()
df["desviacion_v_norm"] = df["ventas_normalizadas"].std()
df

   id  ventas  media_ventas
0   1     769         460.6
1   2     137         460.6
2   3     329         460.6
3   4     464         460.6
4   5     662         460.6
5   6     537         460.6
6   7     875         460.6
7   8     382         460.6
8   9     126         460.6
9  10     325         460.6
   id  ventas  media_ventas  mediana_ventas
0   1     769         460.6           423.0
1   2     137         460.6           423.0
2   3     329         460.6           423.0
3   4     464         460.6           423.0
4   5     662         460.6           423.0
5   6     537         460.6           423.0
6   7     875         460.6           423.0
7   8     382         460.6           423.0
8   9     126         460.6           423.0
9  10     325         460.6           423.0
   id  ventas  media_ventas  mediana_ventas  desviacion_ventas
0   1     769         460.6           423.0         252.059605
1   2     137         460.6           423.0         252.059605
2   3     329      

id  ventas  media_ventas  mediana_ventas  desviacion_ventas  \
0   1     769         460.6           423.0         252.059605   
1   2     137         460.6           423.0         252.059605   
2   3     329         460.6           423.0         252.059605   
3   4     464         460.6           423.0         252.059605   
4   5     662         460.6           423.0         252.059605   
5   6     537         460.6           423.0         252.059605   
6   7     875         460.6           423.0         252.059605   
7   8     382         460.6           423.0         252.059605   
8   9     126         460.6           423.0         252.059605   
9  10     325         460.6           423.0         252.059605   

   ventas_normalizadas  media_v_norm  desviacion_v_norm  
0             1.223520     -0.149171                1.0  
1            -1.283823     -0.149171                1.0  
2            -0.522099     -0.149171                1.0  
3             0.013489     -0.149171                1.0  
4             0.799017     -0.149171                1.0  
5             0.303103     -0.149171                1.0  
6             1.644056     -0.149171                1.0  
7            -0.311831     -0.149171                1.0  
8            -1.327464     -0.149171                1.0  
9            -0.537968     -0.149171                1.0

In [81]:
df = pd.read_csv("ShipmentLine_v3.csv")
order = np.array(df["order.orderIdentifier"])
value = np.array(df["value"])
order_normz = (order - order.mean()) / order.std()
print(order_normz)
print(order_normz.mean())
print(order_normz.std())


[-2.13437472 -2.13437472 -2.13437472 -2.13437472 -2.13437472 -2.13437472
 -2.13437473 -2.13437473 -2.13437473 -2.13437473 -2.13437473 -2.13437473
 -2.13437474 -2.13437474 -2.13437474 -2.13437474 -2.13437474 -2.13437474
 -2.13437475 -2.13437475 -2.13437475 -2.13437475 -2.13437475 -2.13437475
 -2.13437476 -2.13437476 -2.13437476 -2.13437476 -2.13437476 -2.13437476
 -2.13437477 -2.13437477 -2.13437477 -2.13437477 -2.13437477 -2.13437477
  0.46852084  0.46852085  0.46852085  0.46852086  0.46852086  0.46852087
  0.46852089  0.46852091  0.46852092  0.46852092  0.46852093  0.46852093
  0.46852095  0.46852096  0.468521    0.468521    0.46852101  0.46852101
  0.46852103  0.46852105  0.46852106  0.46852106  0.46852106  0.46852108
  0.4685211   0.4685211   0.46852111  0.46852111  0.46852111  0.46852111
  0.46852115  0.46852116  0.46852117  0.46852117  0.46852118  0.46852119
  0.4685212   0.46852123  0.46852126  0.46852127  0.46852131  0.46852134
  0.46852135  0.46852135  0.46852135  0.46852137  0

In [82]:
value_normz = (value - value.mean()) / value.std()
print(value_normz)
print(value_normz.mean())
print(value_normz.std())

[ 1.76715088e+00 -4.07216848e-01 -4.07216848e-01  7.23454368e-01
 -4.07216848e-01 -4.07216848e-01 -4.95881954e-03 -4.07216848e-01
 -4.07216848e-01 -3.75743354e-02 -4.07216848e-01 -4.07216848e-01
 -1.13677206e-01 -4.07216848e-01 -4.07216848e-01  3.09895111e+00
 -4.07216848e-01 -4.07216848e-01 -8.64976092e-02 -4.07216848e-01
 -4.07216848e-01 -2.87626624e-01 -4.07216848e-01 -4.07216848e-01
  1.33227733e+00 -4.07216848e-01 -4.07216848e-01  1.33227733e+00
 -4.07216848e-01 -4.07216848e-01 -2.06087834e-01 -4.07216848e-01
 -4.07216848e-01  2.66837146e-01 -4.07216848e-01 -4.07216848e-01
 -4.03042062e-01 -1.61861194e-01  2.25959033e-01 -3.96971228e-01
 -4.00258872e-01  9.70462541e-01 -1.85048652e-01 -4.03042062e-01
 -3.30679105e-01 -3.48978583e-01 -1.24722994e-01 -3.41429179e-01
 -4.05599119e-01  1.05064187e-01  7.28830540e+00  2.06898791e+00
 -1.44205329e-01  2.25959033e-01 -3.37637081e-01 -1.24722994e-01
  7.28830540e+00  1.38376636e+00 -4.05599119e-01 -2.37442217e-01
 -3.37637081e-01  9.50980

In [16]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "id": range(1, 12),
    "ventas": np.random.randint(20, 50, size=11),
    "ventas2": np.arange(0,11)
})
df["percentil_25"] = df["ventas2"].quantile(0.25) 
df["percentil_50"] = df["ventas2"].quantile(0.5)
df["percentil_80"] = df["ventas2"].quantile(0.8)
df["min_ventas"] = df["ventas2"].min() 
df["max_ventas"] = df["ventas2"].max()
df


id  ventas  ventas2  percentil_25  percentil_50  percentil_80  min_ventas  \
0    1      31        0           2.5           5.0           8.0           0   
1    2      49        1           2.5           5.0           8.0           0   
2    3      46        2           2.5           5.0           8.0           0   
3    4      35        3           2.5           5.0           8.0           0   
4    5      34        4           2.5           5.0           8.0           0   
5    6      34        5           2.5           5.0           8.0           0   
6    7      49        6           2.5           5.0           8.0           0   
7    8      38        7           2.5           5.0           8.0           0   
8    9      37        8           2.5           5.0           8.0           0   
9   10      41        9           2.5           5.0           8.0           0   
10  11      48       10           2.5           5.0           8.0           0   

    max_ventas  
0           10  
1           10  
2           10  
3           10  
4           10  
5           10  
6           10  
7           10  
8           10  
9           10  
10          10