- ¿Qué es NumPy y para qué se utiliza en programación científica?
- Historia de Numpy
- ¿Cuál es la diferencia entre una lista de Python y un array de NumPy?
- ¿Cómo se crea un array en NumPy? Explicar y dar ejemplos de:
    - Un array unidimensional.
    - Un array bidimensional.
    - Un array de valores inicializados con ceros, unos y valores aleatorios.
- ¿Cómo acceder a los elementos de un array y cómo modificar sus valores?
- ¿Qué son los **ejes (axis)** en un array multidimensional? Explica con ejemplos prácticos.
- Explica la diferencia entre **np.dot()** (producto escalar) y **np.cross()** (producto cruzado).
- ¿Cómo se pueden transformar las dimensiones de un array? Explica con ejemplos las funciones `reshape()` y `flatten()`.
- ¿Qué es Matplotlib y en qué situaciones se usa en programación?

NumPy es una biblioteca de Python utilizada en computación científica y análisis de datos. Permite trabajar con grandes matrices y arrays, realizando operaciones matemáticas complejas de forma rápida y eficiente. Es fundamental en áreas como el análisis de datos, procesamiento de imágenes, aprendizaje automático y visualización de datos.

Python no fue diseñado inicialmente para computación numérica, pero en 1995 surgió el grupo SIG matrix-sig con el objetivo de crear un paquete para computación de vectores. Guido van Rossum, creador de Python, extendió la sintaxis del lenguaje para facilitar este tipo de cálculos. Jim Hugunin desarrolló una primera implementación llamada Numeric, que luego fue ampliada y conocida como las "extensiones numéricas de Python". Posteriormente, se creó Numarray, como un reemplazo más flexible de Numeric, pero ambos paquetes fueron reemplazados por NumPy en 2006, desarrollado por Travis Oliphant, quien unificó las características de ambos. NumPy se separó de SciPy y se lanzó como un paquete independiente. En 2011, se añadió soporte para Python 3, y ese mismo año PyPy comenzó a trabajar en una implementación de la API de NumPy. NumPy se consolidó como una herramienta esencial en computación científica y análisis de datos.

La diferencia principal entre una lista de Python y un array de NumPy es la eficiencia y el propósito. Los arrays de NumPy son más rápidos y eficientes para realizar cálculos numéricos, ya que están optimizados para trabajar con grandes cantidades de datos. Mientras que las listas de Python pueden contener elementos de diferentes tipos (como números y cadenas), los arrays de NumPy son homogéneos, es decir, todos sus elementos deben ser del mismo tipo, generalmente numérico. Además, NumPy permite realizar operaciones matemáticas de forma más sencilla y rápida sobre todo el array, mientras que en las listas de Python tendrías que hacerlo manualmente. También, NumPy ofrece muchas funciones matemáticas avanzadas que no están disponibles en las listas de Python. Por lo tanto, NumPy es más adecuado para tareas de computación científica y análisis de grandes datos, mientras que las listas son más flexibles para otros usos.

Para crear un array en NumPy, primero debes importar la biblioteca usando import numpy as np. Luego, puedes usar varias funciones de NumPy, como np.array(), np.zeros(), np.ones(), y np.random.random() para crear arrays de diferentes formas y tipos.

1. Array unidimensional
Un array unidimensional es simplemente una lista de elementos organizados en una sola fila. Para crear un array unidimensional en NumPy, usamos la función np.array() pasando una lista de Python.
Ejemplo:

In [1]:
import numpy as np

# Array unidimensional
array_unidimensional = np.array([1, 2, 3, 4, 5])
print(array_unidimensional)

[1 2 3 4 5]


2. Array bidimensional
Un array bidimensional es una estructura de datos organizada en filas y columnas, como una matriz. Para crear un array bidimensional en NumPy, pasamos una lista de listas a la función np.array().

Ejemplo:

In [2]:
import numpy as np

# Array bidimensional (matriz 2x3)
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6]])
print(array_bidimensional)

[[1 2 3]
 [4 5 6]]


3. Array con valores inicializados con ceros, unos y valores aleatorios
Array de ceros: Se usa la función np.zeros(), que crea un array de cualquier forma, pero con todos sus elementos inicializados a cero.
Ejemplo:

In [3]:
import numpy as np

# Array de ceros (3x3)
array_zeros = np.zeros((3, 3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Array de unos: Se usa la función np.ones(), que crea un array con todos sus elementos inicializados a uno.
Ejemplo:

In [4]:
import numpy as np

# Array de unos (2x4)
array_ones = np.ones((2, 4))
print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Array de valores aleatorios: Se usa la función np.random.random(), que crea un array con valores aleatorios entre 0 y 1.
Ejemplo:

In [5]:
import numpy as np

# Array con valores aleatorios (2x3)
array_random = np.random.random((2, 3))
print(array_random)

[[0.27730225 0.8142494  0.25341525]
 [0.93562944 0.03302134 0.63915149]]


En NumPy, puedes acceder a los elementos de un array de manera similar a cómo lo haces con listas de Python, pero con algunas características adicionales debido a la naturaleza de los arrays multidimensionales. Puedes acceder a elementos utilizando índices y, si es necesario, también modificar sus valores directamente.

1. Acceder a los elementos de un array
Array unidimensional
Para acceder a los elementos de un array unidimensional, puedes usar el índice del elemento dentro del array, empezando desde 0 para el primer elemento.

Ejemplo:

In [6]:
import numpy as np

# Array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Acceder al primer elemento (índice 0)
print(array[0]) 

# Acceder al último elemento (índice -1)
print(array[-1])

10
50


Array bidimensional
Para acceder a los elementos de un array bidimensional (como una matriz), se usa una tupla de índices: primero el índice de la fila y luego el de la columna.

Ejemplo:

In [7]:
import numpy as np

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Acceder al elemento en la primera fila, segunda columna (índice 0, 1)
print(array_2d[0, 1]) 

# Acceder al elemento en la segunda fila, tercera columna (índice 1, 2)
print(array_2d[1, 2]) 


2
6


Acceder a un rango de elementos
Puedes usar la notación de slicing para acceder a un rango de elementos en arrays unidimensionales o multidimensionales.

Ejemplo:

In [8]:
import numpy as np

# Array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Acceder a un rango de elementos (índices del 1 al 3, excluyendo el 4)
print(array[1:4])


[20 30 40]


En un array bidimensional:

In [ ]:
import numpy as np

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Acceder a las dos primeras filas, todas las columnas
print(array_2d[:2, :])

2. Modificar los valores de un array
Para modificar un elemento específico de un array, puedes asignar un nuevo valor al índice o rango de índices que deseas cambiar. Al igual que en las listas, NumPy permite modificar elementos de arrays directamente.

Modificar un solo elemento
Puedes cambiar el valor de un elemento especificando su índice.

Ejemplo:

In [ ]:
import numpy as np

# Array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Modificar el tercer elemento (índice 2)
array[2] = 100
print(array) 


Modificar un rango de elementos
También puedes modificar un rango de elementos usando slicing.

Ejemplo:

In [9]:
import numpy as np

# Array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Modificar un rango de elementos (índices 1 a 3)
array[1:4] = [200, 300, 400]
print(array) 

[ 10 200 300 400  50]


Modificar un array bidimensional
En un array bidimensional, puedes modificar los valores de una fila, columna o elemento específico.

Ejemplo:

In [10]:
import numpy as np

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Modificar el elemento en la primera fila, segunda columna
array_2d[0, 1] = 100
print(array_2d)

# Modificar toda la segunda fila
array_2d[1, :] = [7, 8, 9]
print(array_2d)


[[  1 100   3]
 [  4   5   6]]
[[  1 100   3]
 [  7   8   9]]


En NumPy, los ejes (axis) son una forma de referirse a las dimensiones de un array multidimensional. Cada eje representa una dirección a lo largo de una de las dimensiones del array, y puedes realizar operaciones a lo largo de estos ejes de manera eficiente. En un array bidimensional, por ejemplo, tienes dos ejes: uno para las filas y otro para las columnas. Los ejes son importantes porque muchas funciones en NumPy, como sum(), mean(), y otras, permiten operar a lo largo de un eje específico.

Ejes en un array multidimensional
Eje 0 (axis=0): Representa las filas en un array bidimensional. Si realizas una operación a lo largo de este eje, estás operando sobre las filas.
Eje 1 (axis=1): Representa las columnas en un array bidimensional. Si realizas una operación a lo largo de este eje, estás operando sobre las columnas.
En arrays de dimensiones superiores, los ejes siguen la misma lógica, donde el eje 0 es la primera dimensión, el eje 1 es la segunda, y así sucesivamente
Ejemplo:

In [11]:
import numpy as np

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Sumar a lo largo del eje 0 (filas)
# Esto sumará los elementos de cada columna
print(np.sum(array_2d, axis=0)) 

# Sumar a lo largo del eje 1 (columnas)
# Esto sumará los elementos de cada fila
print(np.sum(array_2d, axis=1)) 

[5 7 9]
[ 6 15]


La función np.dot() realiza el producto escalar entre dos vectores, devolviendo un número. Es útil para cálculos como la proyección o el ángulo entre vectores. La función np.cross(), en cambio, realiza el producto cruzado entre dos vectores en 3D, devolviendo un vector perpendicular a los dos vectores originales. El producto cruzado se utiliza para encontrar áreas de paralelogramos y en aplicaciones de física en 3D. Ejemplo: 

In [12]:
import numpy as np

# Vectores
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Producto escalar
producto_escalar = np.dot(A, B)
print("Producto escalar (np.dot()):", producto_escalar) 

# Producto cruzado
producto_cruzado = np.cross(A, B)
print("Producto cruzado (np.cross()):", producto_cruzado) 


Producto escalar (np.dot()): 32
Producto cruzado (np.cross()): [-3  6 -3]


Las funciones reshape() y flatten() de NumPy permiten transformar las dimensiones de un array.

reshape(): Cambia la forma de un array sin modificar sus datos, ajustando sus dimensiones. El número total de elementos debe mantenerse constante.

Ejemplo:

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshape = arr.reshape(2, 3)  # Cambia a 2 filas y 3 columnas
print(arr_reshape)

[[1 2 3]
 [4 5 6]]


flatten(): Convierte un array multidimensional en un array unidimensional.

Ejemplo:

In [14]:
arr_flatten = arr_reshape.flatten()  # Convierte a un array 1D
print(arr_flatten)

[1 2 3 4 5 6]


Matplotlib es una biblioteca de Python que nos permite crear gráficos y visualizaciones de datos de manera sencilla. Es muy útil en análisis de datos, ya que nos ayuda a entender mejor la información al mostrarla de forma visual. Puedes hacer desde gráficos de líneas hasta diagramas de dispersión, barras o histogramas, dependiendo de lo que necesites mostrar.

Se usa principalmente cuando quieres visualizar datos para detectar patrones, tendencias o hacer comparaciones. Por ejemplo, en ciencia de datos, física, estadísticas o incluso en aprendizaje automático, donde a menudo necesitamos ver cómo se comportan los datos antes de tomar decisiones o crear modelos.